CREATE TABLE KHACHHANG_ONLINE(
USERNAME varchar(10) PRIMARY KEY NOT NULL,
HOTEN varchar(50) NOT NULL,
EMAIL INT(10),
SDT varchar(12),
PASS varchar(50) NOT NULL
)ENGINE= InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;