CREATE TABLE KHACHHANG_ONLINE(
USERNAME varchar(10) PRIMARY KEY NOT NULL,
HOTEN varchar(100) NOT NULL,
EMAIL varchar(100),
SDT INT(12),
PASS varchar(50) NOT NULL
)ENGINE= InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO KHACHHANG_ONLINE(USERNAME, HOTEN,EMAIL, SDT,PASS) VALUES
('nvt', 'Nguyễn Văn Tài','nvt@gmail.com' ,0113456789, '12345')